# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  private_lane :asc_api_key do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_PATH"]
    )
  end
  
  desc "Install the App Store certificate and profile (creates them on first run)"
  lane :certificates do
    asc_api_key
    match(readonly: is_ci)
  end
  
  desc "Run unit and UI tests on a simulator"
  lane :test do
    run_tests(scheme: "PolyFeed")
  end

  desc "Build and upload a new build to TestFlight"
  lane :beta do
    setup_ci
    asc_api_key
    match(readonly: is_ci)

    build_number = latest_testflight_build_number + 1

    build_app(
      scheme: "PolyFeed",
      xcargs: "CURRENT_PROJECT_VERSION=#{build_number}"
    )

    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

end
